# SETTINGS

# FILE PATHS
SAVE_PATH:
  - "videos/"
  - "livestreams/"

# STREAM URL
STREAM_URL: "http://__IP__....."

# SPEED LIMIT
SPEED_LIMIT: 60.0

# INFERENCE
ALPHA: 0.3
CONF_THRESHOLD: 0.5
IOU_THRESHOLD: 0.5

# COLORS
COLORS:
  LINE_COLOR: [0, 0, 0] # black
  BOX_COLOR: [0, 255, 0] # green
  TEXT_COLOR: [255, 255, 255] # white
  CENTER_COLOR: [0, 0, 255] # red
  OVERLAY_COLOR: [144, 238, 144] # light green
  TRAPEZOID_COLOR: [153, 255, 255] # light yellow

# STYLES
FONT_SCALE: 1.3
THICKNESS: 2

# LOGS
LOG_FILE: "logs/info.log"
SAVE_SPEEDING_CARS_PATH: "logs/speeding_cars"

# CAMERA
RES_W: 1280
RES_H: 720
FORMAT: "RGB888"